name: 'Build package'
description: 'Build testplan package'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.30.1

    - run: pip install --upgrade setuptools build
      shell: bash
    - run: |
        cd testplan/web_ui/testing
        pnpm install
        pnpm config set enable-pre-post-scripts true
        CI=false pnpm build
        cd -
      shell: bash  
    - run: python -m build -w
      shell: bash
