language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install pylint
  - python setup.py develop
  - python install-testplan-ui --verbose --dev

script:
  - pylint --rcfile pylintrc testplan
  - pytest tests --verbose

