language: python

cache: pip

python:
  - "2.7"
  - "3.4"

install:
  - pip install -r requirements.txt -U
  - python install-testplan-ui --verbose --dev

script:
  - pylint --rcfile pylintrc testplan
  - pytest tests --verbose -n 8

