site_name: ReleaseHerald

theme:
  name: material
  palette:
    scheme: default
    primary: green

markdown_extensions:
  - def_list
  - mkdocs-click
  - admonition
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

plugins:
  - search
  - awesome-pages
  - mermaid2
  - mkdocstrings:
      watch:
        - releaseherald/plugins
      handlers:
        python:
          selection:
            docstring_style: google

