site_name: ReleaseHerald

theme:
  name: material
  palette:
    scheme: default
    primary: green

markdown_extensions:
  - def_list
  - mkdocs-click
  - admonition

plugins:
  - search
  - awesome-pages
