name: 'Restore pip cache'
description: 'Restore pip cache for the project'
runs:
  using: "composite"
  steps:
    - name: Restore Pip Cache
      uses: actions/cache@v4
      with:
        path: ${{ runner.os == 'Linux' && '~/.cache/pip' || '~\AppData\Local\pip\Cache' }}
        key: ${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
