name: Cut new version

on:
  workflow_dispatch:

jobs:

  cut-new-version:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.11'

      - run: pip install --upgrade bumpver
      - run: pip install ./releaseherald
      
      - name: git setup
        run: |
          git config user.name "Github Version Updater" 
          git config user.email "<>"
      - run: bumpver update
      - run: bumpver show --env > new-version.txt
      - run: releaseherald generate --latest --no-update -t news.rst
      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: new-version
          path: |
            new-version.txt
            news.rst

  build:
    runs-on: ubuntu-latest
    needs: cut-new-version

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - run: git pull origin
      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: new-version
      - name: Get Version
        id: get_version
        run: |
          eval $(cat new-version.txt)
          echo "new_version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/build-package
      - uses: ./.github/actions/create-release
        with:
          tag_name: ${{ steps.get_version.outputs.new_version }}
          package: dist/testplan-${{ steps.get_version.outputs.new_version }}-py3-none-any.whl
          news: news.rst
